### ISSUE TITLE
Switching display setting does not work.

### ISSUE THREAD

**Issue by Atlinx** [AlexDarigan/WAT-Mono#18]
I've downloaded the latest release of WAT and when I switch the display setting for WAT to anything other than Bottom Panel, the plugin will display a blank dock.

The image below shows what happens when I switch to the "Left.UL Dock" option.

![image](https://user-images.githubusercontent.com/25368491/113439678-078f5980-93b9-11eb-89e8-5a6a8d33eff4.png)

**Comment by AlexDarigan** [comment]
Could you take a screenshot of the entire editor screen here?

**Comment by Atlinx** [comment]
Here's a gif of my entire editor screen:
![WAT-Mono-Dock-Broken](https://user-images.githubusercontent.com/25368491/113731413-c653be00-96c6-11eb-94d3-6a5df63421b4.gif)

**Comment by AlexDarigan** [comment]
This was my bad. This is a bug in an older version and it turns out I hadn't actually released WAT Mono 5.0 until right now (despite thinking I realized this earlier). The latest release should fix this.
