### ISSUE TITLE
Running tests outside of the editor through the "Tests" menu does not work

### ISSUE THREAD

**Issue by Atlinx** [AlexDarigan/WAT-Mono#21]
**Version:**
v5.0.0

When running tests using the "Tests" menu with the "In Editor" option unselected, the test runner runs and then immediately crashes.

Running tests "In Editor" or with the command line still works.

![WatMono-Launch-Tests-Bug](https://user-images.githubusercontent.com/25368491/114327691-1c31c700-9b08-11eb-8922-254170fb29e6.gif)

**Comment by AlexDarigan** [comment]
Does this issue also exist in master?

**Comment by Atlinx** [comment]
This issue is fixed in master.
